spring:
  kafka:
    bootstrap-servers: kafka:9092
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/______
    username: postgres
    password: ______
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: false

server:
  port: 8082

topics: data-temperature,data-power,data-voltage
